name: Example workflow using SOOS
on: workflow_dispatch
jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v2.0.0
      with:
        project_name: "My Project Name"
        directories_to_exclude: "**bin/start/**, **/start/**"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://dev-api.soos.io/api/"